# Generated by Django 5.0.3 on 2024-03-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_category_tbl_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_contact', models.CharField(max_length=30)),
                ('staff_email', models.CharField(max_length=30)),
                ('staff_address', models.CharField(max_length=30)),
                ('staff_photo', models.FileField(upload_to='Staff/')),
            ],
        ),
    ]
