# Generated by Django 5.0.3 on 2024-03-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_staff',
            name='staff_photo',
            field=models.FileField(upload_to='Assets/Staff/'),
        ),
    ]
