# Generated by Django 5.0.3 on 2024-03-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_delete_tbl_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_staff',
        ),
    ]
