# Generated by Django 5.0.3 on 2024-03-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_tbl_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_contact', models.CharField(max_length=30)),
                ('staff_email', models.CharField(max_length=30)),
                ('staff_address', models.CharField(max_length=30)),
                ('staff_photo', models.FileField(upload_to='Assets/Staff/')),
                ('staff_password', models.CharField(max_length=30)),
            ],
        ),
    ]
