# Generated by Django 5.0.3 on 2024-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=30)),
                ('document_description', models.CharField(max_length=30)),
                ('document_image', models.FileField(upload_to='Assets/Documents/')),
            ],
        ),
    ]
