# Generated by Django 5.0.3 on 2024-04-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_document'),
        ('Guest', '0007_remove_tbl_user_place_delete_tbl_complaint_and_more'),
        ('Staff', '0003_remove_tbl_journal_staff_delete_tbl_book_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.DeleteModel(
            name='tbl_document',
        ),
        migrations.DeleteModel(
            name='tbl_staff',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
