# Generated by Django 5.0.3 on 2024-03-31 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_staff'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=30)),
                ('journal_volume', models.CharField(max_length=30)),
                ('journal_publisher', models.CharField(max_length=30)),
                ('journal_topic', models.CharField(max_length=50)),
                ('journal_image', models.FileField(upload_to='Assets/journal_images/')),
                ('journal_price', models.IntegerField()),
                ('journal_status', models.IntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
            ],
        ),
    ]
