# Generated by Django 5.0.3 on 2024-04-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_initial'),
        ('Staff', '0003_remove_tbl_journal_staff_delete_tbl_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('book_publisher', models.CharField(max_length=30)),
                ('book_description', models.CharField(max_length=100)),
                ('book_image', models.FileField(upload_to='Assets/book_images/')),
                ('book_price', models.IntegerField()),
                ('book_status', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=30)),
                ('journal_volume', models.CharField(max_length=30)),
                ('journal_publisher', models.CharField(max_length=30)),
                ('journal_topic', models.CharField(max_length=50)),
                ('journal_image', models.FileField(upload_to='Assets/journal_images/')),
                ('journal_price', models.IntegerField()),
                ('journal_status', models.IntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
            ],
        ),
    ]
