# Generated by Django 5.0.3 on 2024-03-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
