# Generated by Django 5.0.3 on 2024-04-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_complaint'),
        ('User', '0004_remove_tbl_journal_booking_journal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
