# Generated by Django 5.0.3 on 2024-04-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_journal_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_journal_booking',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='tbl_journal_booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_book_booking',
        ),
        migrations.DeleteModel(
            name='tbl_journal_booking',
        ),
    ]
